-- MySQL Script generated by MySQL Workbench
-- Wed Oct  4 17:58:26 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dw
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dw` DEFAULT CHARACTER SET utf8 ;
USE `dw` ;

-- -----------------------------------------------------
-- Table `dw`.`DIM_FILME`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw`.`DIM_FILME` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_filme` VARCHAR(45) NOT NULL,
  `ator_principal` VARCHAR(120) NOT NULL,
  `qt_duracao` DECIMAL(3,2) NOT NULL,
  `ds_genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw`.`DIM_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw`.`DIM_CLIENTE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw`.`DIM_ VENDEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw`.`DIM_ VENDEDOR` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_vendedor` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw`.`DIM_TEMPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw`.`DIM_TEMPO` (
  `data_reference` INT NOT NULL AUTO_INCREMENT,
  `ano` INT NOT NULL,
  `trimestre` INT NOT NULL,
  `mes` VARCHAR(45) NOT NULL,
  `data_da_semana` VARCHAR(45) NOT NULL,
  `flag_feriado` TINYTEXT NOT NULL,
  PRIMARY KEY (`data_reference`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw`.`FATO_LOCACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw`.`FATO_LOCACAO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `qt_locacao` INT NOT NULL,
  `vl_locacao` DECIMAL(5,2) NOT NULL,
  `DIM_FILME_id` INT NOT NULL,
  `DIM_CLIENTE_id` INT NOT NULL,
  `DIM_ VENDEDOR_id` INT NOT NULL,
  `DIM_TEMPO_data_reference` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_FATO_LOCACAO_DIM_FILME_idx` (`DIM_FILME_id` ASC) VISIBLE,
  INDEX `fk_FATO_LOCACAO_DIM_CLIENTE1_idx` (`DIM_CLIENTE_id` ASC) VISIBLE,
  INDEX `fk_FATO_LOCACAO_DIM_ VENDEDOR1_idx` (`DIM_ VENDEDOR_id` ASC) VISIBLE,
  INDEX `fk_FATO_LOCACAO_DIM_TEMPO1_idx` (`DIM_TEMPO_data_reference` ASC) VISIBLE,
  CONSTRAINT `fk_FATO_LOCACAO_DIM_FILME`
    FOREIGN KEY (`DIM_FILME_id`)
    REFERENCES `dw`.`DIM_FILME` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FATO_LOCACAO_DIM_CLIENTE1`
    FOREIGN KEY (`DIM_CLIENTE_id`)
    REFERENCES `dw`.`DIM_CLIENTE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FATO_LOCACAO_DIM_ VENDEDOR1`
    FOREIGN KEY (`DIM_ VENDEDOR_id`)
    REFERENCES `dw`.`DIM_ VENDEDOR` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FATO_LOCACAO_DIM_TEMPO1`
    FOREIGN KEY (`DIM_TEMPO_data_reference`)
    REFERENCES `dw`.`DIM_TEMPO` (`data_reference`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
